### ISSUE TITLE
Support for `testcode` and `testoutput` in `DocTestDirectiveParser`s

### ISSUE THREAD

**Issue by davidselassie** [simplistix/sybil#110]
I'd love to have support for the `testcode` and `testoutput` directives from `sphinx.ext.doctest` since we already have a good amount of long-form documentation that uses them and like to be able to add some explanatory text before the output, which is harder to do with `doctest` blocks. You said in the docs adding more doctest features wouldn't be hard, so thought I'd ask! Thanks for your work!

**Comment by cjw296** [comment]
Can you point me at some of this documentation (specifically it's source code!) so I have some examples to code against?

**Comment by cjw296** [comment]
@davidselassie - nudge ^^

**Comment by cjw296** [comment]
Hmm, okay, so its not actually doctest you're after but support for your own auto-generated test stuff?
I'm not sure it makes sense to support `testcode` and `testoutput` in `DocTestDirectiveParser` itself, since, as best I can tell, `sphinx.ext.doctest` is ReST only; I can't find any mention of it in the MyST docs, can you point me to them?

I'm also concerned about adding official support for these directives given the complication of "groups", "skipif", "pyversion" and whatever else is lurking there.

I also appear to have been mistaken that `sphinx.ext.doctest` was deprecated, I think?

If all of the above is correct, why not knock up your own parsers using the appropriate directive lexers, etc?
If that would work, I just need to crank out a release with the nested Markdown block parsing...

**Comment by cjw296** [comment]
Okay, closing for now as there's been now followup.

**Comment by cjw296** [comment]
https://pypi.org/project/sybil/6.1.0/ out now, let me know how you get on with creating your own parsers! :-)
