### ISSUE TITLE
Escapes inside docstring cause Sybil to fail

### ISSUE THREAD

**Issue by taminomara** [simplistix/sybil#119]
I noticed that if I use string escapes in docstrings, Sybil fails to evaluate them. Minimal example is this:

```python
def decorator(fn):
    """
    Example:

    >>> @foo
    ... def decorated():
    ...     \"\"\"docstring of a decorated function\"\"\"

    """
```

Sybil fails with SyntaxError: unexpected character after line continuation character.

I'm using `sybil==6.1.1` and `Python 3.12.2`.

**Comment by taminomara** [comment]
Am I correct that Sybil is not aware of Python syntax, and just looks through the sources using regular expressions? If so, I'll switch to using raw docstrings to avoid escapes, but still I'd like to see this fixed.

**Comment by cjw296** [comment]
> Sybil fails with SyntaxError: unexpected character after line continuation character.

Please can you provide a full traceback.

You are correct that Sybil is agnostic to Python syntax, however for docstrings the `ast` module [is used to parse python source code and extract docstring](https://github.com/simplistix/sybil/blob/3e1f3913f41cc484d3a60e3ab3da1a58c3057da0/sybil/document.py#L212)s.

it may be that this is a quick fix, so that full traceback would be very useful.

**Comment by cjw296** [comment]
Here's the docs to literal escaping, so this does feel like a bug in Sybil:
https://docs.python.org/3/reference/lexical_analysis.html#escape-sequences
