### ISSUE TITLE
TypeError related to FixtureManager.getfixtureclosure() on v7.0.0

### ISSUE THREAD

**Issue by gautierronan** [simplistix/sybil#128]
Hi, following the v7.0.0 release, our CI is breaking with a
```
TypeError: FixtureManager.getfixtureclosure() got an unexpected keyword argument 'initialnames'`
```
Our sybil setup is https://github.com/dynamiqs/dynamiqs/blob/main/dynamiqs/conftest.py. Any idea how we could fix this?

The full stack trace is here:
```
../../miniconda3/lib/python3.11/site-packages/_pytest/nodes.py:141: in _create
    return super().__call__(*k, **kw)
../../miniconda3/lib/python3.11/site-packages/sybil/integration/pytest.py:49: in __init__
    self.request_fixtures(sybil.fixtures)
../../miniconda3/lib/python3.11/site-packages/sybil/integration/pytest.py:54: in request_fixtures
    closure = fm.getfixtureclosure(initialnames=names, parentnode=self, ignore_args=set())
E   TypeError: FixtureManager.getfixtureclosure() got an unexpected keyword argument 'initialnames'

During handling of the above exception, another exception occurred:
../../miniconda3/lib/python3.11/site-packages/_pytest/runner.py:341: in from_call
    result: Optional[TResult] = func()
../../miniconda3/lib/python3.11/site-packages/_pytest/runner.py:372: in <lambda>
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
../../miniconda3/lib/python3.11/site-packages/sybil/integration/pytest.py:112: in collect
    yield SybilItem.from_parent(
../../miniconda3/lib/python3.11/site-packages/_pytest/nodes.py:264: in from_parent
    return cls._create(parent=parent, **kw)
../../miniconda3/lib/python3.11/site-packages/_pytest/nodes.py:156: in _create
    return super().__call__(*k, **known_kw)
../../miniconda3/lib/python3.11/site-packages/sybil/integration/pytest.py:49: in __init__
    self.request_fixtures(sybil.fixtures)
../../miniconda3/lib/python3.11/site-packages/sybil/integration/pytest.py:54: in request_fixtures
    closure = fm.getfixtureclosure(initialnames=names, parentnode=self, ignore_args=set())
E   TypeError: FixtureManager.getfixtureclosure() got an unexpected keyword argument 'initialnames'
collected 0 items / 13 errors                                                                                            
```
Thanks!

**Comment by cjw296** [comment]
What version of pytest are you using?

**Comment by cjw296** [comment]
From [your project](https://github.com/dynamiqs/dynamiqs/blob/19ae3973b6690393273574ef63a5490410668a32/pyproject.toml#L51) it looks like version 7, and in my head I'd thought that with drop support for Python 3.7, all folks would be on pytest 8 now.

What's preventing you from moving to pytest 8?

What should Sybil have done differently here? I appreciate I missed the "Requires Python 8+" from the change log, but also don't think there's a way of getting a version solver to spot this, since pytest isn't a required dependency of Sybil?

**Comment by gautierronan** [comment]
Thanks for your quick reply.

Indeed, I tried upgrading to pytest 8 + sybil 7, but the following lines in `conftest.py` are not properly taken into account then (`jnp` is `jax.numpy` which is essentially the same thing as `numpy` in this context). 
```python
@pytest.fixture(scope='session', autouse=True)
def _jax_set_printoptions():
    jnp.set_printoptions(precision=3, suppress=True)
```
This is probably on the side of pytest and not of Sybil though. Will investigate.

> What should Sybil have done differently here? I appreciate I missed the "Requires Python 8+" from the change log, but also don't think there's a way of getting a version solver to spot this, since pytest isn't a required dependency of Sybil?

Indeed I'm not sure anyone is at fault here!

**Comment by pierreguilmin** [comment]
Hi @cjw296, I'm one of the dynamiqs developers as well. Thank you very much for your support! The issue was resolved by explicitely adding all fixtures to `Sybil(..., fixtures=[...])` (see commit https://github.com/dynamiqs/dynamiqs/pull/706/commits/b8abfbe26a2941a8a3e2e69e6e4a1fbce25caeaf). For some reason, this was unnecessary before version 8.

**Comment by cjw296** [comment]
@pierreguilmin - yeah, I was just about to say that fixtures used in Sybil should be explicitly requested.
Honestly, I'm surprised this was working at all before!
