### ISSUE TITLE
Unexpected LexingException when a Markdown (or MyST) document has a comment saying "code"

### ISSUE THREAD

**Issue by adamtheturtle** [simplistix/sybil#145]
Create the following `example.md` and `conftest.py`

```markdown
# example.md

<!-- code -->
```

```python
# conftest.py

from sybil import Sybil
from sybil.parsers.myst import CodeBlockParser

pytest_collect_file = Sybil(parsers=[CodeBlockParser(language='x')], patterns=['*.md']).pytest()
```

Run `pytest example.md` and see:

```pytb
.venv/lib/python3.12/site-packages/sybil/integration/pytest.py:106: in collect
    document = sybil.parse(self.path)
.venv/lib/python3.12/site-packages/sybil/sybil.py:153: in parse
    return type_.parse(str(path), *self.parsers, encoding=self.encoding)
.venv/lib/python3.12/site-packages/sybil/document.py:53: in parse
    for region in parser(document):
.venv/lib/python3.12/site-packages/sybil/parsers/abstract/codeblock.py:54: in __call__
    for region in self.lexers(document):
.venv/lib/python3.12/site-packages/sybil/parsers/abstract/lexers.py:66: in __call__
    raise LexingException(
E   sybil.exceptions.LexingException: Could not match '(?:(?<=\n))?--+>' in /Users/adam/Desktop/sybil-code-example/example.md:
E   ''
```

My understanding is that the Markdown file is valid and so no exception should be raised.

**Comment by adamtheturtle** [comment]
My rough understanding is that this might be because the word `code` is a directive. However, this came up in a real example file and the error was confusing until I narrowed down the file manually.

**Comment by cjw296** [comment]
Okay, so hair splitting, it's a lexing error not a parsing error: the markdown is valid but it doesn't make sense to Sybil.
The error message is confusing, though, so I've made it clearer in https://github.com/simplistix/sybil/commit/86b69472b6b68352234bae888a150073502ed479

What to do about this is tricky, as hiddeny MyST code blocks have always been like this. Options:

1. Change the structure of markdown hidden directive blocks from `<!-- {directive} params  -->` or `% {directive} params` to `<!-- {directive} params  -->` or `% {directive} params` and do a 9.0.0 release, since this is backwards incompatible.

2. Change the markdown hidden code block parsers to allow the list of possible directives to be overridden, meaning you could exclude `code` in your case

3. Do nothing more than change the error message now that it's clearer:

```
E               sybil.exceptions.LexingException: Could not find end of '<!-- code -->\n', looking for '(?:(?<=\n))?--+>' in /Users/chris/vcs/git/sybil/tests/samples/myst-code.md:
E               'This is not a code block.\n'
```

Thoughts? @hynek: do you have an opinion here?

**Comment by adamtheturtle** [comment]
Thank you @cjw296 for working on this. The new error certainly would have made my time easier.

If the choice is to go with (3), a couple of changes would make it even better for the case I hit:

* The error message includes the line number of the start.
* The Sybil documentation (in particular https://sybil.readthedocs.io/en/latest/api.html) describes `sybil.exceptions.LexingException` and what raises it.

**Comment by hynek** [comment]
If you're gonna go with 1, I would recommend to go with some sort of namespace to both avoid collisions and make it clearer what's happening. For example: `<!-- sybil:{directive} params  -->` or `<!-- sybil:directive params  -->` which you could just add as an alternative and not break anything (you could deprecate it, though).

**Comment by cjw296** [comment]
@adamtheturtle - I've [pushed up a change](https://github.com/simplistix/sybil/commit/8f0bbca593750565e11d0d4107793ff192c852a8) to include the starting location.

Documenting `LexingException` seems like a good idea.

I'm inclined to go for option 1, since there's already a [technically breaking change](https://github.com/simplistix/sybil/commit/1b3aad8e9f1abc92325016c4c3d7b3ee4658c27f) coming in the next release. I hope that won't affect many people, and I suspect the same will be true of this change.

I like the idea of an explicit prefix that @hynek suggests, but I seem to remember Sybil is actually an implementation detail for you, @adamtheturtle? If so, would having `sybil` show up in your examples be a problem?

@hynek - I wonder whether the real-world use of this would be clear enough to not need the prefix/namespace? eg:
- `<!-- {skip} start  -->`
- `<!-- {invisible-code-block} python  -->`
- `<!-- {skip} end  -->`

**Comment by adamtheturtle** [comment]
>  If so, would having sybil show up in your examples be a problem?

Ideally for me, there would be no need to have `sybil` show up. Perhaps that could be a parameter somewhere (maybe with `sybil` as the default)?

**Comment by cjw296** [comment]
API docs for `LexingException` added in 17ee34efa845eaa5f5cc8d427379e89548b729c5.

**Comment by adamtheturtle** [comment]
@cjw296 The changes made here would have made my situation clearer and that is plenty for me. I have created https://github.com/simplistix/sybil/pull/147 which would possibly have made it so I would have known to handle the exception before I happened upon a document which caused it to be raised. Thank you again!

**Comment by cjw296** [comment]
Released in https://pypi.org/project/sybil/9.0.0/
